#include <atomic>
#include <cstdio>
#include <set>
#include <vector>

#include "hnswlib.h"

static int fail(const char *message) {
    std::fprintf(stderr, "FAILED: %s\n", message);
    return 1;
}

struct CountingL2 {
    static std::atomic<size_t> calls;

    static float Eval(const void *left, const void *right, size_t, size_t, const void *) {
        ++calls;
        const float delta = *static_cast<const float *>(left) - *static_cast<const float *>(right);
        return delta * delta;
    }

    static void Eval2(const void *left, const void *right_a, const void *right_b,
                      size_t, size_t, size_t, const void *, float &dist_a, float &dist_b) {
        dist_a = Eval(left, right_a, 0, 0, nullptr);
        dist_b = Eval(left, right_b, 0, 0, nullptr);
    }
};

std::atomic<size_t> CountingL2::calls{0};

int main() {
    hnswlib::L2Space space(1);
    hnswlib::HierarchicalNSW<float> index(&space, 3, 2, 10);

    const float tied = 1.0f;
    const float other = 3.0f;
    index.addPoint(&tied, 1);
    index.addPoint(&tied, 0);
    index.addPoint(&other, 2);

    const uint32_t groups[] = {0, 0, 1};
    index.setGroupMap(groups);
    index.setEf(10);

    const float query = 0.0f;
    const auto results = index.searchKnn(&query, 2);
    if (results.size() != 2)
        return fail("grouped search did not return one result per group");

    std::set<hnswlib::labeltype> labels;
    for (const auto &result : results)
        labels.insert(result.second);

    // Group 0 has an exact tie: the lower global vector label must win.
    if (labels != std::set<hnswlib::labeltype>({0, 2}))
        return fail("grouped search did not retain the winning labels");

    // Exercise the full result-list boundary too: the equal-distance lower label
    // must still be admitted when ef is already full.
    hnswlib::HierarchicalNSW<float> tight(&space, 2, 2, 10);
    // Keep label 1 as the entry point on every standard library implementation.
    // Random levels generated by std::default_random_engine are implementation-defined.
    tight.addPoint<void, false>(&tied, 1, 1);
    tight.addPoint<void, false>(&tied, 0, 1);
    const uint32_t one_group[] = {0, 0};
    tight.setGroupMap(one_group);
    tight.setEf(1);
    const auto tied_result = tight.searchKnn(&query, 1);
    if (tied_result.size() != 1 || tied_result.front().second != 0)
        return fail("the lower tied label did not win at a full result boundary");

    // An equal-distance vector from a different group must not replace the
    // group already admitted at the result boundary.
    const uint32_t separate_groups[] = {5, 10};
    tight.setGroupMap(separate_groups);
    const auto separate_result = tight.searchKnn(&query, 1);
    if (separate_result.size() != 1 || separate_result.front().second != 1)
        return fail("an equal-distance new group replaced the admitted group");

    // Equal-distance candidates may update a group winner but must not all be
    // admitted to the graph-expansion frontier. With ef=1, searching
    // this all-equal graph should inspect only a bounded neighborhood instead
    // of walking the entire plateau.
    constexpr size_t plateau_size = 1000;
    hnswlib::HierarchicalNSW<float> plateau(&space, plateau_size, 16, 100, 100);
    std::vector<uint32_t> plateau_groups(plateau_size, 0);
    for (size_t i = 0; i < plateau_size; ++i)
        plateau.addPoint(&tied, i);
    plateau.setGroupMap(plateau_groups.data());
    plateau.setEf(1);

    CountingL2::calls = 0;
    const auto plateau_result = plateau.searchKnn<hnswlib::NoopTerminationState, false, CountingL2>(&query, 1);
    if (plateau_result.size() != 1)
        return fail("the plateau search did not return one grouped result");
    if (CountingL2::calls.load() >= plateau_size / 2)
        return fail("equal-distance candidates expanded an unbounded graph plateau");
    return 0;
}
