name: HNSW CI

on: [push, pull_request]

jobs:
  test_cpp:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5

      - name: Build
        run: |
          cmake -S . -B build
          cmake --build build --config Release
        shell: bash

      - name: Test
        timeout-minutes: 15
        run: ctest --test-dir build -C Release --output-on-failure
